---
# Nginx

- name: Template mongodb.repo
  template: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo mode=0644

- name: install Mongodb
  yum: pkg={{ item }} state=installed enablerepo=mongodb
  with_items:
    - mongo-10gen
    - mongo-10gen-server

- name: ensure mongod is running automatically at boot time
  service: name=mongod state=started enabled=yes
